### ISSUE TITLE
cannot search group accounts in search bar

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#120]
also, on chrome you cannot add new group account if you are on search page

**Comment by dustingtorres** [comment]
Fixed.

**Comment by closurefyre** [comment]
@dustingtorres 
I created a new group called "mollie stones." Did not appear when I searched for it in the nav search  bar. not fixed
